---
- name: Configure Server
  hosts: localhost
  gather_facts: yes
  vars:
    domain: ""

  tasks:

    - name: Clone GitHub repository containing Jinja2 templates
      git:
        repo: 'https://github.com/Mekkawy12/jntfanawsinstance.git'
        dest: '/tmp/nginxdnsansibleconf'
        version: 'master'
        force: yes

    - name: Get current ip
      command: hostname -I
      register: current_ip 

    - name: Update and upgrade yum packages
      ansible.builtin.yum:
        update_cache: yes


    - name: Install nginx
      command: sudo amazon-linux-extras install nginx1

    - name: Install bind9
      command: sudo yum install bind

    - name: Install bind9utils
      command: sudo yum install bind-utils

    - name: Create a directory
      command: sudo mkdir /usr/share/nginx/html/{{ domain }}

    - name: Create index.html
      template: 
        src: /tmp/nginxdnsansibleconf/config/indexfile.j2
        dest: /tmp/index.html
      command: sudo cp /tmp/index.html /usr/share/nginx/html/{{ domain }}/
    

    - name: Create domain
      template: 
        src: /tmp/nginxdnsansibleconf/config/siteconf.j2
        dest: /tmp/{{ domain }}.conf
      command: bash -c "cat /tmp/{{ domain }}.conf | sudo tee -a /etc/nginx/conf.d/{{ domain }}.conf"  

    - name: Update /etc/named.conf
      template: 
        src: /tmp/nginxdnsansibleconf/config/namedconflocal.j2
        dest: /tmp/named.conf
      command: cat /tmp/named.conf | sudo tee -a /etc/named.conf
        

    - name: Create zone file
      template: 
        src: /tmp/nginxdnsansibleconf/config/zonetemplate.j2
        dest: /tmp/{{ domain }}.db
      command: sudo cp /tmp/{{ domain }}.db /etc/named/

    - name: Reload services
      command: bash -c "sudo service nginx restart && sudo service named restart"